#!/usr/bin/env python3
"""Dark Factory: autonomous, receipt-backed software factory demo.

This package targets the Dark Factory hackathon with a narrow but real loop:
plan a clean-room Pocketful payment engine, generate working Python files, run
ruff and pytest, scan generated artifacts, and export a receipt tied to hashes
and tool exit codes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import textwrap
import time
from typing import Any

from guardrails import CouncilGuardrails, ReviewResult


EXPECTED_GENERATED_FILES = (
    "pyproject.toml",
    "README.md",
    "pocketful/__init__.py",
    "pocketful/payments.py",
    "tests/test_payments.py",
)

EXPECTED_SURFACE_NAMES = (
    "Surface 1 (Spec and Scope)",
    "Surface 2 (Quality and Linting)",
    "Surface 3 (Behavioral Verification)",
    "Surface 4 (Security Invariants)",
    "Surface 5 (Delivery)",
)


class SoftwareFactory:
    """Dark Factory core engine."""

    def __init__(self, workspace_dir: str):
        self.workspace_dir = Path(workspace_dir).resolve()
        self.guardrails = CouncilGuardrails(str(self.workspace_dir))
        self.run_log: list[dict[str, str]] = []
        self.generated_files: list[str] = []
        self.surface_results: list[ReviewResult] = []
        self.plan_data: dict[str, Any] = {}

    def log_step(self, phase: str, message: str, status: str = "INFO") -> None:
        entry = {
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "phase": phase,
            "message": message,
            "status": status,
        }
        self.run_log.append(entry)
        print(f"[{entry['timestamp']}] [{phase}] [{status}] {message}", flush=True)

    def plan(self, product_name: str, specification: str) -> dict[str, Any]:
        """Surface 1: validate spec and produce a concrete architecture plan."""
        self.log_step("PLANNING", f"Decomposing specification for '{product_name}'...")
        spec_check = self.guardrails.review_surface_1_spec(product_name, specification)
        self.surface_results.append(spec_check)
        self.log_step(
            "SURFACE_1_SPEC",
            spec_check.details,
            "SUCCESS" if spec_check.passed else "FAILURE",
        )
        if not spec_check.passed:
            raise ValueError(spec_check.details)

        self.plan_data = {
            "product": product_name,
            "architecture": "thread-safe in-memory payment ledger",
            "modules": [
                {"name": "pocketful.payments", "description": "balances, transfer, split rounding"},
                {"name": "tests.test_payments", "description": "money conservation and concurrency"},
                {"name": "README", "description": "demo and verification commands"},
            ],
            "acceptance_criteria": [
                "deterministic cent rounding",
                "failed split payments do not partially mutate balances",
                "idempotency keys prevent duplicate retry transfers",
                "no negative balances",
                "concurrent transfers conserve total money",
                "ruff and pytest pass from the generated workspace",
            ],
        }
        self.log_step("PLANNING", "Architecture plan established with executable checks.", "SUCCESS")
        return self.plan_data

    def _write_file(self, relative_path: str, content: str) -> None:
        path = self.workspace_dir / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(textwrap.dedent(content).lstrip(), encoding="utf-8", newline="\n")
        self.generated_files.append(relative_path.replace("\\", "/"))

    def _pocketful_files(self) -> dict[str, str]:
        return {
            "pyproject.toml": """
                [project]
                name = "pocketful-dark-factory"
                version = "0.1.0"
                description = "Clean-room Pocketful payment ledger generated by Dark Factory"
                requires-python = ">=3.12"

                [tool.ruff]
                line-length = 100
                target-version = "py312"

                [tool.pytest.ini_options]
                testpaths = ["tests"]
                pythonpath = ["."]
            """,
            "README.md": """
                # Pocketful Clean-Room Payment Engine

                Pocketful is a small Venmo-like payment ledger generated by Dark Factory.
                It is not a bank, wallet custody layer, chain integration, or production
                financial system. It demonstrates deterministic cents accounting, split
                payment rounding, and concurrent transfer safety in a local Python package.

                ## Run

                ```bash
                python -m ruff check .
                python -m pytest --basetemp=.pytest_tmp -q
                ```
            """,
            "pocketful/__init__.py": """
                from .payments import LedgerEntry, PocketfulLedger, to_cents

                __all__ = ["LedgerEntry", "PocketfulLedger", "to_cents"]
            """,
            "pocketful/payments.py": r'''
                """Thread-safe payment ledger for the Pocketful clean-room demo."""

                from __future__ import annotations

                from dataclasses import dataclass
                from decimal import Decimal, ROUND_HALF_UP
                import re
                from threading import RLock
                from typing import Iterable


                CENT = Decimal("0.01")
                ADDRESS_RE = re.compile(r"^[a-z][a-z0-9_-]{2,31}$")


                @dataclass(frozen=True)
                class LedgerEntry:
                    sequence: int
                    sender: str
                    recipient: str
                    cents: int
                    memo: str = ""


                def to_cents(amount: Decimal | str | int | float) -> int:
                    """Convert user-facing money into positive integer cents."""
                    value = Decimal(str(amount)).quantize(CENT, rounding=ROUND_HALF_UP)
                    cents = int(value * 100)
                    if cents <= 0:
                        raise ValueError("amount must be positive")
                    return cents


                def _to_non_negative_cents(amount: Decimal | str | int | float) -> int:
                    value = Decimal(str(amount)).quantize(CENT, rounding=ROUND_HALF_UP)
                    cents = int(value * 100)
                    if cents < 0:
                        raise ValueError("amount cannot be negative")
                    return cents


                def _validate_address(address: str) -> str:
                    normalized = str(address).strip().lower()
                    if not ADDRESS_RE.fullmatch(normalized):
                        raise ValueError(f"invalid account address: {address!r}")
                    return normalized


                class PocketfulLedger:
                    """In-memory payment ledger with atomic transfer semantics."""

                    def __init__(self) -> None:
                        self._balances: dict[str, int] = {}
                        self._entries: list[LedgerEntry] = []
                        self._idempotency: dict[str, tuple[str, tuple[LedgerEntry, ...]]] = {}
                        self._lock = RLock()

                    def create_account(
                        self,
                        address: str,
                        opening_balance: Decimal | str | int | float = "0.00",
                    ) -> None:
                        normalized = _validate_address(address)
                        cents = _to_non_negative_cents(opening_balance)
                        if cents < 0:
                            raise ValueError("opening balance cannot be negative")
                        with self._lock:
                            if normalized in self._balances:
                                raise ValueError("account already exists")
                            self._balances[normalized] = cents

                    def balance_cents(self, address: str) -> int:
                        normalized = _validate_address(address)
                        with self._lock:
                            return self._balances[normalized]

                    def total_cents(self) -> int:
                        with self._lock:
                            return sum(self._balances.values())

                    def entries(self) -> tuple[LedgerEntry, ...]:
                        with self._lock:
                            return tuple(self._entries)

                    def transfer(
                        self,
                        sender: str,
                        recipient: str,
                        amount: Decimal | str | int | float,
                        memo: str = "",
                        idempotency_key: str | None = None,
                    ) -> LedgerEntry:
                        cents = to_cents(amount)
                        sender_id = _validate_address(sender)
                        recipient_id = _validate_address(recipient)
                        fingerprint = f"transfer:{sender_id}:{recipient_id}:{cents}:{memo}"
                        with self._lock:
                            cached = self._idempotent_result(idempotency_key, fingerprint)
                            if cached is not None:
                                return cached[0]
                            entry = self._transfer_cents(sender_id, recipient_id, cents, memo)
                            self._remember_idempotency(idempotency_key, fingerprint, (entry,))
                            return entry

                    def split_payment(
                        self,
                        sender: str,
                        recipients: Iterable[str],
                        total: Decimal | str | int | float,
                        memo: str = "split",
                        idempotency_key: str | None = None,
                    ) -> tuple[LedgerEntry, ...]:
                        sender_id = _validate_address(sender)
                        normalized_recipients = [_validate_address(item) for item in recipients]
                        if not normalized_recipients:
                            raise ValueError("split requires at least one recipient")
                        total_cents = to_cents(total)
                        base, remainder = divmod(total_cents, len(normalized_recipients))
                        amounts = [
                            base + (1 if index < remainder else 0)
                            for index in range(len(normalized_recipients))
                        ]
                        fingerprint = (
                            f"split:{sender_id}:{','.join(normalized_recipients)}:{total_cents}:{memo}"
                        )
                        with self._lock:
                            cached = self._idempotent_result(idempotency_key, fingerprint)
                            if cached is not None:
                                return cached
                            self._preflight_transfers(
                                sender_id,
                                tuple(zip(normalized_recipients, amounts, strict=True)),
                                total_cents,
                            )
                            entries = tuple(
                                self._apply_transfer_cents(sender_id, recipient, cents, memo)
                                for recipient, cents in zip(normalized_recipients, amounts, strict=True)
                            )
                            self._remember_idempotency(idempotency_key, fingerprint, entries)
                            return entries

                    def _transfer_cents(
                        self,
                        sender: str,
                        recipient: str,
                        cents: int,
                        memo: str,
                    ) -> LedgerEntry:
                        sender_id = _validate_address(sender)
                        recipient_id = _validate_address(recipient)
                        self._preflight_transfers(sender_id, ((recipient_id, cents),), cents)
                        return self._apply_transfer_cents(sender_id, recipient_id, cents, memo)

                    def _preflight_transfers(
                        self,
                        sender_id: str,
                        transfers: tuple[tuple[str, int], ...],
                        total_cents: int,
                    ) -> None:
                        if sender_id not in self._balances:
                            raise KeyError("unknown account")
                        seen_recipients: set[str] = set()
                        for recipient_id, cents in transfers:
                            if recipient_id == sender_id:
                                raise ValueError("sender and recipient must differ")
                            if recipient_id in seen_recipients:
                                raise ValueError("duplicate split recipient")
                            seen_recipients.add(recipient_id)
                            if recipient_id not in self._balances:
                                raise KeyError("unknown account")
                            if cents <= 0:
                                raise ValueError("amount must be positive")
                        if self._balances[sender_id] < total_cents:
                            raise ValueError("insufficient funds")

                    def _apply_transfer_cents(
                        self,
                        sender_id: str,
                        recipient_id: str,
                        cents: int,
                        memo: str,
                    ) -> LedgerEntry:
                        self._balances[sender_id] -= cents
                        self._balances[recipient_id] += cents
                        entry = LedgerEntry(
                            sequence=len(self._entries) + 1,
                            sender=sender_id,
                            recipient=recipient_id,
                            cents=cents,
                            memo=str(memo)[:120],
                        )
                        self._entries.append(entry)
                        return entry

                    def _idempotent_result(
                        self,
                        idempotency_key: str | None,
                        fingerprint: str,
                    ) -> tuple[LedgerEntry, ...] | None:
                        if idempotency_key is None:
                            return None
                        existing = self._idempotency.get(str(idempotency_key))
                        if existing is None:
                            return None
                        existing_fingerprint, entries = existing
                        if existing_fingerprint != fingerprint:
                            raise ValueError("idempotency key reused with different operation")
                        return entries

                    def _remember_idempotency(
                        self,
                        idempotency_key: str | None,
                        fingerprint: str,
                        entries: tuple[LedgerEntry, ...],
                    ) -> None:
                        if idempotency_key is not None:
                            self._idempotency[str(idempotency_key)] = (fingerprint, entries)
            ''',
            "tests/test_payments.py": """
                from concurrent.futures import ThreadPoolExecutor

                import pytest

                from pocketful import PocketfulLedger, to_cents


                @pytest.fixture
                def ledger_with_accounts() -> PocketfulLedger:
                    ledger = PocketfulLedger()
                    ledger.create_account("alice", "1000.00")
                    ledger.create_account("bob", "0.00")
                    ledger.create_account("carla", "0.00")
                    ledger.create_account("dina", "0.00")
                    return ledger


                def test_to_cents_rejects_zero_and_negative_amounts() -> None:
                    assert to_cents("1.235") == 124
                    with pytest.raises(ValueError):
                        to_cents("0")
                    with pytest.raises(ValueError):
                        to_cents("-0.01")


                def test_split_payment_rounds_without_losing_money(
                    ledger_with_accounts: PocketfulLedger,
                ) -> None:
                    ledger = ledger_with_accounts
                    before = ledger.total_cents()
                    entries = ledger.split_payment("alice", ["bob", "carla", "dina"], "10.00")
                    assert [entry.cents for entry in entries] == [334, 333, 333]
                    assert ledger.balance_cents("alice") == 99000
                    assert ledger.balance_cents("bob") == 334
                    assert ledger.balance_cents("carla") == 333
                    assert ledger.balance_cents("dina") == 333
                    assert ledger.total_cents() == before


                def test_insufficient_funds_does_not_mutate_balances(
                    ledger_with_accounts: PocketfulLedger,
                ) -> None:
                    ledger = ledger_with_accounts
                    before_balances = {
                        name: ledger.balance_cents(name)
                        for name in ("alice", "bob", "carla", "dina")
                    }
                    with pytest.raises(ValueError):
                        ledger.transfer("bob", "alice", "0.01")
                    assert {
                        name: ledger.balance_cents(name)
                        for name in ("alice", "bob", "carla", "dina")
                    } == before_balances
                    assert ledger.entries() == ()


                def test_split_with_missing_recipient_is_atomic(
                    ledger_with_accounts: PocketfulLedger,
                ) -> None:
                    ledger = ledger_with_accounts
                    before_balances = {
                        name: ledger.balance_cents(name)
                        for name in ("alice", "bob", "carla", "dina")
                    }
                    with pytest.raises(KeyError):
                        ledger.split_payment("alice", ["bob", "missing"], "2.00")
                    assert {
                        name: ledger.balance_cents(name)
                        for name in ("alice", "bob", "carla", "dina")
                    } == before_balances
                    assert ledger.entries() == ()


                def test_split_with_sender_as_recipient_is_atomic(
                    ledger_with_accounts: PocketfulLedger,
                ) -> None:
                    ledger = ledger_with_accounts
                    before_balances = {
                        name: ledger.balance_cents(name)
                        for name in ("alice", "bob", "carla", "dina")
                    }
                    with pytest.raises(ValueError):
                        ledger.split_payment("alice", ["bob", "alice"], "2.00")
                    assert {
                        name: ledger.balance_cents(name)
                        for name in ("alice", "bob", "carla", "dina")
                    } == before_balances
                    assert ledger.entries() == ()


                def test_opening_balance_uses_half_up_rounding() -> None:
                    ledger = PocketfulLedger()
                    ledger.create_account("alice", "1.005")
                    assert ledger.balance_cents("alice") == 101


                def test_transfer_idempotency_key_prevents_duplicate_retry(
                    ledger_with_accounts: PocketfulLedger,
                ) -> None:
                    ledger = ledger_with_accounts
                    first = ledger.transfer("alice", "bob", "1.00", idempotency_key="retry-1")
                    second = ledger.transfer("alice", "bob", "1.00", idempotency_key="retry-1")
                    assert first == second
                    assert ledger.balance_cents("alice") == 99900
                    assert ledger.balance_cents("bob") == 100
                    assert len(ledger.entries()) == 1
                    with pytest.raises(ValueError):
                        ledger.transfer("alice", "bob", "2.00", idempotency_key="retry-1")


                def test_concurrent_transfers_preserve_money(
                    ledger_with_accounts: PocketfulLedger,
                ) -> None:
                    ledger = ledger_with_accounts
                    before = ledger.total_cents()

                    def send(index: int) -> int:
                        recipient = ["bob", "carla", "dina"][index % 3]
                        return ledger.transfer("alice", recipient, "0.07", memo="load-test").cents

                    with ThreadPoolExecutor(max_workers=12) as pool:
                        moved = list(pool.map(send, range(300)))

                    assert sum(moved) == 2100
                    assert len(ledger.entries()) == 300
                    assert ledger.balance_cents("alice") == 97900
                    assert ledger.total_cents() == before
            """,
        }

    def implement(self, plan: dict[str, Any]) -> list[str]:
        """Generate the Pocketful application and tests into the workspace."""
        self.log_step("IMPLEMENTATION", f"Synthesizing files for {plan['product']}...")
        self.workspace_dir.mkdir(parents=True, exist_ok=True)
        self.generated_files = []

        if str(plan["product"]).lower() != "pocketful":
            raise NotImplementedError("This submission focuses on the Pocketful clean-room track.")

        for relative_path, content in self._pocketful_files().items():
            self._write_file(relative_path, content)

        self.log_step(
            "IMPLEMENTATION",
            f"Materialized {len(self.generated_files)} generated artifacts into {self.workspace_dir}.",
            "SUCCESS",
        )
        return self.generated_files

    def verify_council_surfaces(
        self,
        branch_name: str = "stagent/pocketful-v1",
        commit_msg: str = "feat: implement pocketful payment engine",
    ) -> bool:
        """Run surfaces 2-5 against the generated workspace."""
        self.log_step("VERIFICATION", "Starting Council 5-Surface Guardrail Verification...")

        checks = [
            ("SURFACE_2_QUALITY", self.guardrails.review_surface_2_quality(self.generated_files)),
            ("SURFACE_3_TESTS", self.guardrails.review_surface_3_harness()),
            ("SURFACE_4_SECURITY", self.guardrails.review_surface_4_security(self.generated_files)),
            (
                "SURFACE_5_DELIVERY",
                self.guardrails.review_surface_5_delivery(branch_name, commit_msg, self.generated_files),
            ),
        ]

        for phase, result in checks:
            self.surface_results.append(result)
            self.log_step(phase, result.details, "SUCCESS" if result.passed else "FAILURE")
        verified = all(result.passed for _, result in checks)
        self.log_step(
            "VERIFICATION",
            "All Council Review Surfaces PASSED." if verified else "Council verification failed.",
            "SUCCESS" if verified else "FAILURE",
        )
        return verified

    def file_hashes(self) -> dict[str, str]:
        hashes: dict[str, str] = {}
        for rel_path in self.generated_files:
            data = (self.workspace_dir / rel_path).read_bytes()
            hashes[rel_path] = hashlib.sha256(data).hexdigest()
        return hashes

    def export_run_receipt(self, output_path: str) -> dict[str, Any]:
        """Export verifiable execution artifact for hackathon judges."""
        hashes = self.file_hashes()
        surface_names = [result.surface_name for result in self.surface_results]
        files_complete = (
            tuple(self.generated_files) == EXPECTED_GENERATED_FILES
            and set(hashes) == set(EXPECTED_GENERATED_FILES)
            and all((self.workspace_dir / path).exists() for path in EXPECTED_GENERATED_FILES)
        )
        surfaces_complete = (
            set(surface_names) == set(EXPECTED_SURFACE_NAMES)
            and len(surface_names) == len(EXPECTED_SURFACE_NAMES)
        )
        verified = (
            bool(self.plan_data)
            and files_complete
            and surfaces_complete
            and all(result.passed for result in self.surface_results)
        )
        receipt = {
            "schema_version": "dark_factory.run_receipt.v2",
            "factory_version": "1.1.0-darkfactory",
            "council_architecture": "5-surface-guardrail",
            "claim_boundary": "local_demo_evidence_not_production_readiness",
            "workspace": str(self.workspace_dir),
            "plan": self.plan_data,
            "generated_files": self.generated_files,
            "expected_generated_files": list(EXPECTED_GENERATED_FILES),
            "file_sha256": hashes,
            "surface_results": [result.to_receipt() for result in self.surface_results],
            "completeness": {
                "files_complete": files_complete,
                "surfaces_complete": surfaces_complete,
                "expected_surface_names": list(EXPECTED_SURFACE_NAMES),
                "observed_surface_names": surface_names,
            },
            "execution_trace": self.run_log,
            "total_steps": len(self.run_log),
            "verified": verified,
        }
        Path(output_path).write_text(json.dumps(receipt, indent=2), encoding="utf-8", newline="\n")
        self.log_step("EXPORT", f"Execution run receipt saved to {output_path}", "SUCCESS")
        return receipt


def main() -> None:
    parser = argparse.ArgumentParser(description="Dark Factory Autonomous Software Factory")
    parser.add_argument("--track", choices=["pocketful"], default="pocketful")
    parser.add_argument("--workspace", default="./workspace")
    parser.add_argument("--output-receipt", default="./run_receipt.json")
    args = parser.parse_args()

    specs = {
        "pocketful": (
            "Build a secure clean-room payment and wallet ledger with balance tracking, "
            "transaction records, split-payment rounding, and concurrent money conservation."
        )
    }

    factory = SoftwareFactory(args.workspace)
    product = args.track.capitalize()
    print("================================================================")
    print(f"[DARK FACTORY] Starting Dark Factory for {product}")
    print("================================================================")

    plan = factory.plan(product, specs[args.track])
    factory.implement(plan)
    verified = factory.verify_council_surfaces()
    factory.export_run_receipt(args.output_receipt)

    print("================================================================")
    print(f"[COMPLETE] Dark Factory Run Complete. Verified: {verified}")
    print("================================================================")
    if not verified:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
